name: carpenter_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.70.1
  intl: ^0.20.1
  image_picker: ^1.1.2
  image: ^4.5.2
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1
  dependency_validator: ^5.0.2
  direct_dialer: ^2.0.1
  path_provider: ^2.1.5
  flutter_lints: ^5.0.0
  flutter_sound: ^9.19.1
  permission_handler: ^11.3.1
  sqflite: ^2.4.1

flutter:
  uses-material-design: true
  assets:
  - assets/
